/*
 * App URI: emp/emp_main_page
 * Source Location: emp/emp_main_page.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("emp/emp_main_page", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * emp_main_page.js
			 * Created at 2022. 1. 4. 오전 11:16:09.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["1fr"]);
			formLayout_1.setRows(["80px", "1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container();
				// Layout
				var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
				group_2.setLayout(responsiveXYLayout_1);
				(function(container){
					var image_1 = new cpr.controls.Image();
					image_1.src = "theme/img/time-left.png";
					(function(image_1){
					})(image_1);
					container.addChild(image_1, {
						positions: [
							{
								"media": "all and (min-width: 1024px)",
								"top": "10px",
								"left": "42px",
								"width": "146px",
								"height": "60px"
							}, 
							{
								"media": "all and (min-width: 500px) and (max-width: 1023px)",
								"hidden": false,
								"top": "10px",
								"left": "21px",
								"width": "71px",
								"height": "60px"
							}, 
							{
								"media": "all and (max-width: 499px)",
								"hidden": false,
								"top": "10px",
								"left": "14px",
								"width": "50px",
								"height": "60px"
							}
						]
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var group_3 = new cpr.controls.Container();
				// Layout
				var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
				group_3.setLayout(verticalLayout_1);
				(function(container){
					var group_4 = new cpr.controls.Container();
					// Layout
					var xYLayout_2 = new cpr.controls.layouts.XYLayout();
					group_4.setLayout(xYLayout_2);
					(function(container){
					})(group_4);
					container.addChild(group_4, {
						"width": "400px",
						"height": "84px"
					});
					var output_1 = new cpr.controls.Output();
					output_1.value = "매장 관리";
					output_1.style.css({
						"text-align" : "center"
					});
					container.addChild(output_1, {
						"width": "100px",
						"height": "20px"
					});
					var output_2 = new cpr.controls.Output();
					output_2.value = "사원 관리";
					output_2.style.css({
						"text-align" : "center"
					});
					container.addChild(output_2, {
						"autoSize": "none",
						"width": "240px",
						"height": "20px"
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "승인 요청";
					output_3.style.css({
						"text-align" : "center"
					});
					container.addChild(output_3, {
						"autoSize": "none",
						"width": "240px",
						"height": "20px"
					});
				})(group_3);
				container.addChild(group_3, {
					"colIndex": 0,
					"rowIndex": 1
				});
			})(group_1);
			container.addChild(group_1, {
				"top": "10px",
				"bottom": "10px",
				"left": "10px",
				"width": "240px"
			});
			
			var mDIFolder_1 = new cpr.controls.MDIFolder("mdi1");
			
			var tabItem_1 = (function(tabFolder){
				var tabItem_1 = new cpr.controls.TabItem();
				tabItem_1.text = "사원 관리";
				var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea1");
				cpr.core.App.load("emp/ptj_list", function(app) {
					if(app){
						embeddedApp_1.app = app;
					}
				});
				tabItem_1.content = embeddedApp_1;
				return tabItem_1;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_1);
			
			var tabItem_2 = (function(tabFolder){
				var tabItem_2 = new cpr.controls.TabItem();
				tabItem_2.text = "홍길동";
				var embeddedApp_2 = new cpr.controls.EmbeddedApp("ea2");
				cpr.core.App.load("emp/ptj_information", function(app) {
					if(app){
						embeddedApp_2.app = app;
					}
				});
				tabItem_2.content = embeddedApp_2;
				return tabItem_2;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_2);
			
			var tabItem_3 = (function(tabFolder){
				var tabItem_3 = new cpr.controls.TabItem();
				tabItem_3.text = "승인요청 리스트";
				var embeddedApp_3 = new cpr.controls.EmbeddedApp("ea3");
				cpr.core.App.load("emp/ptj_approval_request", function(app) {
					if(app){
						embeddedApp_3.app = app;
					}
				});
				tabItem_3.content = embeddedApp_3;
				return tabItem_3;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_3);
			
			var tabItem_4 = (function(tabFolder){
				var tabItem_4 = new cpr.controls.TabItem();
				tabItem_4.text = "매장 관리";
				var embeddedApp_4 = new cpr.controls.EmbeddedApp("ea4");
				cpr.core.App.load("emp/store_list", function(app) {
					if(app){
						embeddedApp_4.app = app;
					}
				});
				tabItem_4.content = embeddedApp_4;
				return tabItem_4;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_4);
			mDIFolder_1.setSelectedTabItem(tabItem_1);
			container.addChild(mDIFolder_1, {
				"top": "90px",
				"right": "20px",
				"bottom": "10px",
				"left": "250px"
			});
			
			var group_5 = new cpr.controls.Container();
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			group_5.setLayout(verticalLayout_2);
			(function(container){
				var group_6 = new cpr.controls.Container();
				// Layout
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.scrollable = false;
				formLayout_2.topMargin = "5px";
				formLayout_2.rightMargin = "5px";
				formLayout_2.bottomMargin = "5px";
				formLayout_2.leftMargin = "5px";
				formLayout_2.horizontalSpacing = "10px";
				formLayout_2.verticalSpacing = "10px";
				formLayout_2.setColumns(["1fr", "100px"]);
				formLayout_2.setRows(["1fr"]);
				group_6.setLayout(formLayout_2);
				(function(container){
					var output_4 = new cpr.controls.Output();
					output_4.value = "로그아웃";
					output_4.style.css({
						"text-align" : "center"
					});
					container.addChild(output_4, {
						"colIndex": 1,
						"rowIndex": 0
					});
				})(group_6);
				container.addChild(group_6, {
					"width": "400px",
					"height": "30px"
				});
				var group_7 = new cpr.controls.Container();
				// Layout
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.scrollable = false;
				formLayout_3.topMargin = "10px";
				formLayout_3.rightMargin = "10px";
				formLayout_3.bottomMargin = "10px";
				formLayout_3.leftMargin = "10px";
				formLayout_3.horizontalSpacing = "10px";
				formLayout_3.verticalSpacing = "10px";
				formLayout_3.setColumns(["100px", "1fr"]);
				formLayout_3.setRows(["1fr"]);
				group_7.setLayout(formLayout_3);
				(function(container){
				})(group_7);
				container.addChild(group_7, {
					"autoSize": "none",
					"width": "754px",
					"height": "38px"
				});
			})(group_5);
			container.addChild(group_5, {
				"top": "10px",
				"right": "20px",
				"left": "250px",
				"height": "81px"
			});
		}
	});
	app.title = "emp_main_page";
	cpr.core.Platform.INSTANCE.register(app);
})();
