/*
 * App URI: emp/ptj_list
 * Source Location: emp/ptj_list.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("emp/ptj_list", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * 사원리스트.js
			 * Created at 2022. 1. 4. 오후 2:34:45.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsptjList");
			dataSet_1.parseData({
				"columns": [
					{"name": "이름"},
					{"name": "연락처"},
					{"name": "급여 형태"},
					{"name": "매장이름"},
					{"name": "총 근무 시간"},
					{"name": "총 급여"},
					{"name": "월급날"},
					{"name": "세금 여부"}
				],
				"rows": [
					{"이름": "이름1", "연락처": "연락처1", "급여 형태": "급여 형태1", "매장이름": "매장이름1", "총 근무 시간": "총 근무 시간1", "총 급여": "총 급여1", "월급날": "월급날1", "세금 여부": "세금 여부1"},
					{"이름": "이름2", "연락처": "연락처2", "급여 형태": "급여 형태2", "매장이름": "매장이름2", "총 근무 시간": "총 근무 시간2", "총 급여": "총 급여2", "월급날": "월급날2", "세금 여부": "세금 여부2"},
					{"이름": "이름3", "연락처": "연락처3", "급여 형태": "급여 형태3", "매장이름": "매장이름3", "총 근무 시간": "총 근무 시간3", "총 급여": "총 급여3", "월급날": "월급날3", "세금 여부": "세금 여부3"},
					{"이름": "이름4", "연락처": "연락처4", "급여 형태": "급여 형태4", "매장이름": "매장이름4", "총 근무 시간": "총 근무 시간4", "총 급여": "총 급여4", "월급날": "월급날4", "세금 여부": "세금 여부4"},
					{"이름": "이름5", "연락처": "연락처5", "급여 형태": "급여 형태5", "매장이름": "매장이름5", "총 근무 시간": "총 근무 시간5", "총 급여": "총 급여5", "월급날": "월급날5", "세금 여부": "세금 여부5"},
					{"이름": "이름6", "연락처": "연락처6", "급여 형태": "급여 형태6", "매장이름": "매장이름6", "총 근무 시간": "총 근무 시간6", "총 급여": "총 급여6", "월급날": "월급날6", "세금 여부": "세금 여부6"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "2px";
			formLayout_1.rightMargin = "2px";
			formLayout_1.bottomMargin = "2px";
			formLayout_1.leftMargin = "2px";
			formLayout_1.horizontalSpacing = "2px";
			formLayout_1.verticalSpacing = "2px";
			formLayout_1.setColumns(["150px", "1fr", "1fr", "1fr"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container();
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.scrollable = false;
			formLayout_2.topMargin = "0px";
			formLayout_2.rightMargin = "0px";
			formLayout_2.bottomMargin = "0px";
			formLayout_2.leftMargin = "0px";
			formLayout_2.horizontalSpacing = "0px";
			formLayout_2.verticalSpacing = "0px";
			formLayout_2.setColumns(["100px", "1fr", "150px", "1fr"]);
			formLayout_2.setRows(["1fr"]);
			group_2.setLayout(formLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "매장 선택";
				output_1.style.css({
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var comboBox_1 = new cpr.controls.ComboBox("cmb1");
				(function(comboBox_1){
					comboBox_1.addItem(new cpr.controls.Item("전체", "all"));
				})(comboBox_1);
				container.addChild(comboBox_1, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "오늘 기준 급여";
				output_2.style.css({
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"colIndex": 2,
					"rowIndex": 0
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "Output";
				output_3.format = "s#,##0";
				container.addChild(output_3, {
					"colIndex": 3,
					"rowIndex": 0
				});
			})(group_2);
			container.addChild(group_2, {
				"width": "400px",
				"height": "35px"
			});
			
			var group_3 = new cpr.controls.Container();
			// Layout
			var formLayout_3 = new cpr.controls.layouts.FormLayout();
			formLayout_3.scrollable = false;
			formLayout_3.topMargin = "5px";
			formLayout_3.rightMargin = "5px";
			formLayout_3.bottomMargin = "5px";
			formLayout_3.leftMargin = "5px";
			formLayout_3.horizontalSpacing = "5px";
			formLayout_3.verticalSpacing = "5px";
			formLayout_3.setColumns(["1fr"]);
			formLayout_3.setRows(["30px", "1fr"]);
			group_3.setLayout(formLayout_3);
			(function(container){
				var grid_1 = new cpr.controls.Grid("grd1");
				grid_1.init({
					"dataSet": app.lookup("dsptjList"),
					"columns": [
						{"width": "25px"},
						{"width": "50px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.filterable = false;
									cell.sortable = false;
									cell.columnType = "checkbox";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.filterable = false;
									cell.sortable = false;
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.targetColumnName = "이름";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.targetColumnName = "연락처";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "연락처";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.targetColumnName = "급여 형태";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "급여 형태";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.targetColumnName = "매장이름";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "매장이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.targetColumnName = "총 근무 시간";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "총 근무 시간";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.targetColumnName = "총 급여";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "총 급여";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.targetColumnName = "월급날";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "월급날";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 9},
								"configurator": function(cell){
									cell.targetColumnName = "세금 여부";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "세금 여부";
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.columnType = "checkbox";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.columnType = "rowindex";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.columnName = "이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.columnName = "연락처";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.columnName = "급여 형태";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.columnName = "매장이름";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.columnName = "총 근무 시간";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.columnName = "총 급여";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.columnName = "월급날";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 9},
								"configurator": function(cell){
									cell.columnName = "세금 여부";
								}
							}
						]
					}
				});
				container.addChild(grid_1, {
					"colIndex": 0,
					"rowIndex": 1
				});
				var group_4 = new cpr.controls.Container();
				// Layout
				var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_2.distribution = "trailing";
				group_4.setLayout(verticalLayout_2);
				(function(container){
					var userDefinedControl_1 = new udc.crudUDC();
					container.addChild(userDefinedControl_1, {
						"width": "300px",
						"height": "30px"
					});
				})(group_4);
				container.addChild(group_4, {
					"colIndex": 0,
					"rowIndex": 0
				});
			})(group_3);
			container.addChild(group_3, {
				"width": "400px",
				"height": "500px"
			});
		}
	});
	app.title = "ptj_list";
	cpr.core.Platform.INSTANCE.register(app);
})();
