/*
 * App URI: emp/ptj_approval_request
 * Source Location: emp/ptj_approval_request.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("emp/ptj_approval_request", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * approval_request_page.js
			 * Created at 2022. 1. 4. 오후 4:02:43.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsRequest");
			dataSet_1.parseData({
				"columns": [
					{
						"name": "name",
						"dataType": "string"
					},
					{"name": "call"},
					{"name": "gender"},
					{"name": "account_name"},
					{"name": "account_number"},
					{
						"name": "birthday",
						"dataType": "string"
					},
					{"name": "approval"},
					{"name": "column1"},
					{"name": "column2"},
					{"name": "column3"}
				],
				"rows": [
					{"name": "name1", "call": "call1", "gender": "gender1", "account_name": "account_name1", "account_number": "account_number1", "birthday": "birthday1"},
					{"name": "name2", "call": "call2", "gender": "gender2", "account_name": "account_name2", "account_number": "account_number2", "birthday": "birthday2"},
					{"name": "name3", "call": "call3", "gender": "gender3", "account_name": "account_name3", "account_number": "account_number3", "birthday": "birthday3", "approval": "approval3", "column1": "column13", "column2": "column23", "column3": "column33"},
					{"name": "name4", "call": "call4", "gender": "gender4", "account_name": "account_name4", "account_number": "account_number4", "birthday": "birthday4", "approval": "approval4", "column1": "column14", "column2": "column24", "column3": "column34"},
					{"name": "name5", "call": "call5", "gender": "gender5", "account_name": "account_name5", "account_number": "account_number5", "birthday": "birthday5", "approval": "approval5", "column1": "column15", "column2": "column25", "column3": "column35"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "0px";
			formLayout_1.setColumns(["150px", "50px", "1fr", "100px", "100px", "100px"]);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "승인 요청수 ";
				output_1.style.css({
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "삭제";
				container.addChild(button_1, {
					"colIndex": 4,
					"rowIndex": 0
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "저장";
				container.addChild(button_2, {
					"colIndex": 5,
					"rowIndex": 0
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "5";
				output_2.style.css({
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "30px"
			});
			
			var group_2 = new cpr.controls.Container();
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.scrollable = false;
			formLayout_2.topMargin = "2px";
			formLayout_2.rightMargin = "2px";
			formLayout_2.bottomMargin = "2px";
			formLayout_2.leftMargin = "2px";
			formLayout_2.horizontalSpacing = "2px";
			formLayout_2.verticalSpacing = "2px";
			formLayout_2.setColumns(["500px", "1fr"]);
			formLayout_2.setRows(["1fr"]);
			group_2.setLayout(formLayout_2);
			(function(container){
				var grid_1 = linker.grid_1 = new cpr.controls.Grid("grd1");
				grid_1.readOnly = true;
				grid_1.init({
					"dataSet": app.lookup("dsRequest"),
					"columns": [
						{"width": "25px"},
						{"width": "50px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"},
						{"width": "100px"}
					],
					"header": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.filterable = false;
									cell.sortable = false;
									cell.columnType = "checkbox";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.filterable = false;
									cell.sortable = false;
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.targetColumnName = "name";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "name";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.targetColumnName = "call";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "call";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.targetColumnName = "gender";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "gender";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.targetColumnName = "account_name";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "account_name";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.targetColumnName = "account_number";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "account_number";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.targetColumnName = "birthday";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "birthday";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.targetColumnName = "approval";
									cell.filterable = false;
									cell.sortable = false;
									cell.text = "approval";
								}
							}
						]
					},
					"detail": {
						"rows": [{"height": "24px"}],
						"cells": [
							{
								"constraint": {"rowIndex": 0, "colIndex": 0},
								"configurator": function(cell){
									cell.columnType = "checkbox";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 1},
								"configurator": function(cell){
									cell.columnType = "rowindex";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 2},
								"configurator": function(cell){
									cell.columnName = "name";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 3},
								"configurator": function(cell){
									cell.columnName = "call";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 4},
								"configurator": function(cell){
									cell.columnName = "gender";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 5},
								"configurator": function(cell){
									cell.columnName = "account_name";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 6},
								"configurator": function(cell){
									cell.columnName = "account_number";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 7},
								"configurator": function(cell){
									cell.columnName = "birthday";
								}
							},
							{
								"constraint": {"rowIndex": 0, "colIndex": 8},
								"configurator": function(cell){
									cell.columnName = "approval";
								}
							}
						]
					}
				});
				container.addChild(grid_1, {
					"colIndex": 1,
					"rowIndex": 0
				});
				var group_3 = linker.group_3 = new cpr.controls.Container();
				group_3.style.setClasses(["cl-form-group"]);
				// Layout
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.scrollable = false;
				formLayout_3.topMargin = "2px";
				formLayout_3.rightMargin = "2px";
				formLayout_3.bottomMargin = "2px";
				formLayout_3.leftMargin = "2px";
				formLayout_3.horizontalSpacing = "2px";
				formLayout_3.verticalSpacing = "2px";
				formLayout_3.horizontalSeparatorWidth = 1;
				formLayout_3.verticalSeparatorWidth = 1;
				formLayout_3.setColumns(["100px", "1fr"]);
				formLayout_3.setUseColumnShade(0, true);
				formLayout_3.setRows(["25px", "25px", "25px", "1fr"]);
				group_3.setLayout(formLayout_3);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "시급";
					container.addChild(output_3, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "주휴수당";
					container.addChild(output_4, {
						"colIndex": 0,
						"rowIndex": 1
					});
					var output_5 = new cpr.controls.Output();
					output_5.value = "세금";
					container.addChild(output_5, {
						"colIndex": 0,
						"rowIndex": 2
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "Output";
					container.addChild(output_6, {
						"colIndex": 0,
						"rowIndex": 3
					});
					var inputBox_1 = new cpr.controls.InputBox("ipb1");
					inputBox_1.bind("value").toDataColumn("column1");
					container.addChild(inputBox_1, {
						"colIndex": 1,
						"rowIndex": 0
					});
					var inputBox_2 = new cpr.controls.InputBox("ipb2");
					inputBox_2.bind("value").toDataColumn("column2");
					container.addChild(inputBox_2, {
						"colIndex": 1,
						"rowIndex": 1
					});
					var inputBox_3 = new cpr.controls.InputBox("ipb3");
					inputBox_3.bind("value").toDataColumn("column3");
					container.addChild(inputBox_3, {
						"colIndex": 1,
						"rowIndex": 2
					});
					var inputBox_4 = new cpr.controls.InputBox("ipb4");
					container.addChild(inputBox_4, {
						"colIndex": 1,
						"rowIndex": 3
					});
				})(group_3);
				container.addChild(group_3, {
					"colIndex": 0,
					"rowIndex": 0
				});
			})(group_2);
			container.addChild(group_2, {
				"width": "400px",
				"height": "200px"
			});
			// Linking
			linker.group_3.setBindContext(new cpr.bind.GridSelectionContext(linker.grid_1));
		}
	});
	app.title = "ptj_approval_request";
	cpr.core.Platform.INSTANCE.register(app);
})();
