/*
 * App URI: ptj/Dialog_date_information
 * Source Location: ptj/Dialog_date_information.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("ptj/Dialog_date_information", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * date_infomation.js
			 * Created at 2022. 1. 4. 오후 5:58:23.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (min-width: 400px) and (max-width: 499px)", "new-screen");
			app.supportMedia("all and (max-width: 399px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "근무 등록";
			output_1.style.css({
				"text-align" : "center"
			});
			container.addChild(output_1, {
				"width": "100px",
				"height": "20px"
			});
			
			var group_1 = new cpr.controls.Container();
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_2);
			(function(container){
				var group_2 = new cpr.controls.Container();
				// Layout
				var formLayout_1 = new cpr.controls.layouts.FormLayout();
				formLayout_1.scrollable = false;
				formLayout_1.topMargin = "5px";
				formLayout_1.rightMargin = "5px";
				formLayout_1.bottomMargin = "5px";
				formLayout_1.leftMargin = "5px";
				formLayout_1.horizontalSpacing = "5px";
				formLayout_1.verticalSpacing = "5px";
				formLayout_1.setColumns(["100px", "1fr", "100px"]);
				formLayout_1.setRows(["1fr"]);
				group_2.setLayout(formLayout_1);
				(function(container){
					var output_2 = new cpr.controls.Output();
					output_2.value = "근무지";
					container.addChild(output_2, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_1 = new cpr.controls.ComboBox("cmb1");
					(function(comboBox_1){
					})(comboBox_1);
					container.addChild(comboBox_1, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_2);
				container.addChild(group_2, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
				var group_3 = new cpr.controls.Container();
				// Layout
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.scrollable = false;
				formLayout_2.topMargin = "5px";
				formLayout_2.rightMargin = "5px";
				formLayout_2.bottomMargin = "5px";
				formLayout_2.leftMargin = "5px";
				formLayout_2.horizontalSpacing = "5px";
				formLayout_2.verticalSpacing = "5px";
				formLayout_2.setColumns(["100px", "1fr", "100px"]);
				formLayout_2.setRows(["1fr"]);
				group_3.setLayout(formLayout_2);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "근무 일자";
					container.addChild(output_3, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var dateInput_1 = new cpr.controls.DateInput("dti1");
					container.addChild(dateInput_1, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_3);
				container.addChild(group_3, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
				var group_4 = new cpr.controls.Container();
				// Layout
				var formLayout_3 = new cpr.controls.layouts.FormLayout();
				formLayout_3.scrollable = false;
				formLayout_3.topMargin = "5px";
				formLayout_3.rightMargin = "5px";
				formLayout_3.bottomMargin = "5px";
				formLayout_3.leftMargin = "5px";
				formLayout_3.horizontalSpacing = "5px";
				formLayout_3.verticalSpacing = "5px";
				formLayout_3.setColumns(["100px", "1fr", "100px"]);
				formLayout_3.setRows(["1fr"]);
				group_4.setLayout(formLayout_3);
				(function(container){
					var output_4 = new cpr.controls.Output();
					output_4.value = "근무 유형";
					container.addChild(output_4, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_2 = new cpr.controls.ComboBox("cmb3");
					(function(comboBox_2){
					})(comboBox_2);
					container.addChild(comboBox_2, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_4);
				container.addChild(group_4, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
				var group_5 = new cpr.controls.Container();
				// Layout
				var flowLayout_1 = new cpr.controls.layouts.FlowLayout();
				group_5.setLayout(flowLayout_1);
				(function(container){
					var output_5 = new cpr.controls.Output();
					output_5.value = "색깔 1";
					container.addChild(output_5, {
						"width": "100px",
						"height": "20px"
					});
					var output_6 = new cpr.controls.Output();
					output_6.value = "색깔 2";
					container.addChild(output_6, {
						"autoSize": "none",
						"width": "100px",
						"height": "20px"
					});
					var output_7 = new cpr.controls.Output();
					output_7.value = "색깔 3";
					container.addChild(output_7, {
						"autoSize": "none",
						"width": "100px",
						"height": "20px"
					});
				})(group_5);
				container.addChild(group_5, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "150px"
			});
			
			var group_6 = new cpr.controls.Container();
			// Layout
			var verticalLayout_3 = new cpr.controls.layouts.VerticalLayout();
			group_6.setLayout(verticalLayout_3);
			(function(container){
				var group_7 = new cpr.controls.Container();
				// Layout
				var formLayout_4 = new cpr.controls.layouts.FormLayout();
				formLayout_4.scrollable = false;
				formLayout_4.topMargin = "5px";
				formLayout_4.rightMargin = "5px";
				formLayout_4.bottomMargin = "5px";
				formLayout_4.leftMargin = "5px";
				formLayout_4.horizontalSpacing = "5px";
				formLayout_4.verticalSpacing = "5px";
				formLayout_4.setColumns(["100px", "1fr", "200px"]);
				formLayout_4.setRows(["1fr"]);
				group_7.setLayout(formLayout_4);
				(function(container){
					var output_8 = new cpr.controls.Output();
					output_8.value = "수당 적용";
					container.addChild(output_8, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var group_8 = new cpr.controls.Container();
					// Layout
					var xYLayout_1 = new cpr.controls.layouts.XYLayout();
					group_8.setLayout(xYLayout_1);
					(function(container){
						var button_1 = new cpr.controls.Button();
						button_1.value = "야간";
						container.addChild(button_1, {
							"top": "0px",
							"left": "0px",
							"width": "67px",
							"height": "20px"
						});
						var button_2 = new cpr.controls.Button();
						button_2.value = "연장";
						container.addChild(button_2, {
							"top": "0px",
							"left": "67px",
							"width": "67px",
							"height": "20px"
						});
						var button_3 = new cpr.controls.Button();
						button_3.value = "특근";
						container.addChild(button_3, {
							"top": "0px",
							"left": "134px",
							"width": "66px",
							"height": "20px"
						});
					})(group_8);
					container.addChild(group_8, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_7);
				container.addChild(group_7, {
					"width": "400px",
					"height": "30px"
				});
				var group_9 = new cpr.controls.Container();
				// Layout
				var formLayout_5 = new cpr.controls.layouts.FormLayout();
				formLayout_5.scrollable = false;
				formLayout_5.topMargin = "5px";
				formLayout_5.rightMargin = "5px";
				formLayout_5.bottomMargin = "5px";
				formLayout_5.leftMargin = "5px";
				formLayout_5.horizontalSpacing = "5px";
				formLayout_5.verticalSpacing = "5px";
				formLayout_5.setColumns(["100px", "1fr", "100px"]);
				formLayout_5.setRows(["1fr"]);
				group_9.setLayout(formLayout_5);
				(function(container){
					var output_9 = new cpr.controls.Output();
					output_9.value = "근무 시간";
					container.addChild(output_9, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_3 = new cpr.controls.ComboBox("cmb2");
					(function(comboBox_3){
					})(comboBox_3);
					container.addChild(comboBox_3, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_9);
				container.addChild(group_9, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
				var group_10 = new cpr.controls.Container();
				// Layout
				var formLayout_6 = new cpr.controls.layouts.FormLayout();
				formLayout_6.scrollable = false;
				formLayout_6.topMargin = "5px";
				formLayout_6.rightMargin = "5px";
				formLayout_6.bottomMargin = "5px";
				formLayout_6.leftMargin = "5px";
				formLayout_6.horizontalSpacing = "5px";
				formLayout_6.verticalSpacing = "5px";
				formLayout_6.setColumns(["100px", "1fr", "100px"]);
				formLayout_6.setRows(["1fr"]);
				group_10.setLayout(formLayout_6);
				(function(container){
					var output_10 = new cpr.controls.Output();
					output_10.value = "휴게 시간";
					container.addChild(output_10, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_4 = new cpr.controls.ComboBox("cmb4");
					(function(comboBox_4){
					})(comboBox_4);
					container.addChild(comboBox_4, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_10);
				container.addChild(group_10, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
				var group_11 = new cpr.controls.Container();
				// Layout
				var formLayout_7 = new cpr.controls.layouts.FormLayout();
				formLayout_7.scrollable = false;
				formLayout_7.topMargin = "5px";
				formLayout_7.rightMargin = "5px";
				formLayout_7.bottomMargin = "5px";
				formLayout_7.leftMargin = "5px";
				formLayout_7.horizontalSpacing = "5px";
				formLayout_7.verticalSpacing = "5px";
				formLayout_7.setColumns(["100px", "1fr", "100px"]);
				formLayout_7.setRows(["1fr"]);
				group_11.setLayout(formLayout_7);
				(function(container){
					var output_11 = new cpr.controls.Output();
					output_11.value = "시급";
					container.addChild(output_11, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var comboBox_5 = new cpr.controls.ComboBox("cmb5");
					(function(comboBox_5){
					})(comboBox_5);
					container.addChild(comboBox_5, {
						"colIndex": 2,
						"rowIndex": 0
					});
				})(group_11);
				container.addChild(group_11, {
					"autoSize": "none",
					"width": "400px",
					"height": "30px"
				});
			})(group_6);
			container.addChild(group_6, {
				"width": "400px",
				"height": "200px"
			});
			
			var group_12 = new cpr.controls.Container();
			// Layout
			var formLayout_8 = new cpr.controls.layouts.FormLayout();
			formLayout_8.scrollable = false;
			formLayout_8.topMargin = "5px";
			formLayout_8.rightMargin = "5px";
			formLayout_8.bottomMargin = "5px";
			formLayout_8.leftMargin = "5px";
			formLayout_8.horizontalSpacing = "5px";
			formLayout_8.verticalSpacing = "5px";
			formLayout_8.setColumns(["1fr", "1fr", "1fr"]);
			formLayout_8.setRows(["1fr"]);
			group_12.setLayout(formLayout_8);
			(function(container){
				var button_4 = new cpr.controls.Button();
				button_4.value = "완료";
				container.addChild(button_4, {
					"colIndex": 0,
					"rowIndex": 0
				});
				var button_5 = new cpr.controls.Button();
				button_5.value = "취소";
				container.addChild(button_5, {
					"colIndex": 2,
					"rowIndex": 0
				});
			})(group_12);
			container.addChild(group_12, {
				"width": "400px",
				"height": "30px"
			});
		}
	});
	app.title = "Dialog_date_information";
	cpr.core.Platform.INSTANCE.register(app);
})();
