/*
 * App URI: ptj/DialogWPM
 * Source Location: ptj/DialogWPM.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("ptj/DialogWPM", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * work_place_management_dialog.js
			 * Created at 2022. 1. 4. 오전 11:34:14.
			 *
			 * @author SeongSoo
			 ************************************************/
			
			
			
			/*
			 * 루트 컨테이너에서 load 이벤트 발생 시 호출.
			 * 앱이 최초 구성된후 최초 랜더링 직후에 발생하는 이벤트 입니다.
			 */
			function onBodyLoad(/* cpr.events.CEvent */ e){
				
				//dataset 선언 
				var dswpn = app.lookup("dsWpName");
				
				console.log(dswpn.getColumnData("wpName"));
				
				for(var i = 0 ; i < dswpn.getRowCount() ; i++){
					var value = dswpn.getValue(i, "wpName");
					//udc 선언
					var wpm = new udc.wpm();
					console.log(value);
					wpm.wp_name = value;
					
					app.lookup("wp_list").addChild(wpm, {
						autoSize : "none",
						height : "100px",
						width : "400px"
					});
				}
			
			
			};
			// End - User Script
			
			// Header
			var dataSet_1 = new cpr.data.DataSet("dsWpName");
			dataSet_1.parseData({
				"columns": [{"name": "wpName"}],
				"rows": [
					{"wpName": "wpName1"},
					{"wpName": "wpName2"},
					{"wpName": "wpName3"},
					{"wpName": "wpName4"},
					{"wpName": "wpName5"},
					{"wpName": "wpName6"},
					{"wpName": "wpName7"},
					{"wpName": "wpName8"},
					{"wpName": "wpName9"},
					{"wpName": "wpName10"}
				]
			});
			app.register(dataSet_1);
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (min-width: 400px) and (max-width: 499px)", "new-screen");
			app.supportMedia("all and (max-width: 399px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.scrollable = false;
			container.setLayout(verticalLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container("wp_list");
			// Layout
			var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
			group_1.setLayout(verticalLayout_2);
			(function(container){
			})(group_1);
			container.addChild(group_1, {
				"width": "400px",
				"height": "400px"
			});
			
			var group_2 = new cpr.controls.Container();
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			responsiveXYLayout_1.scrollable = false;
			group_2.setLayout(responsiveXYLayout_1);
			(function(container){
				var button_1 = new cpr.controls.Button();
				button_1.value = "근무지 추가";
				container.addChild(button_1, {
					positions: [
						{
							"media": "all and (min-width: 1024px)",
							"hidden": false,
							"left": "43px",
							"width": "100px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (min-width: 500px) and (max-width: 1023px)",
							"hidden": false,
							"left": "21px",
							"width": "49px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (min-width: 400px) and (max-width: 499px)",
							"left": "43px",
							"width": "100px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (max-width: 399px)",
							"hidden": false,
							"left": "15px",
							"width": "34px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}
					]
				});
				var button_2 = new cpr.controls.Button();
				button_2.value = "사업장 연결";
				container.addChild(button_2, {
					positions: [
						{
							"media": "all and (min-width: 1024px)",
							"hidden": false,
							"right": "43px",
							"width": "100px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (min-width: 500px) and (max-width: 1023px)",
							"hidden": false,
							"right": "21px",
							"width": "49px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (min-width: 400px) and (max-width: 499px)",
							"right": "43px",
							"width": "100px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}, 
						{
							"media": "all and (max-width: 399px)",
							"hidden": false,
							"right": "15px",
							"width": "34px",
							"height": "22px",
							"top": "calc(50% - 11px)"
						}
					]
				});
			})(group_2);
			container.addChild(group_2, {
				"width": "400px",
				"height": "90px"
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "DialogWPM";
	cpr.core.Platform.INSTANCE.register(app);
})();
