/*
 * App URI: ptj/payslip-part1
 * Source Location: ptj/payslip-part1.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("ptj/payslip-part1", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * payslip-part1.js
			 * Created at 2022. 1. 4. 오후 10:11:49.
			 *
			 * @author ksk19
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"color" : "gainsboro",
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "40px";
			formLayout_1.rightMargin = "40px";
			formLayout_1.bottomMargin = "40px";
			formLayout_1.leftMargin = "40px";
			formLayout_1.horizontalSpacing = "0px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.setColumns(["200px", "1fr"]);
			formLayout_1.setRows(["263px", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.css({
				"text-align" : "center"
			});
			// Layout
			var formLayout_2 = new cpr.controls.layouts.FormLayout();
			formLayout_2.scrollable = false;
			formLayout_2.topMargin = "15px";
			formLayout_2.rightMargin = "15px";
			formLayout_2.bottomMargin = "15px";
			formLayout_2.leftMargin = "15px";
			formLayout_2.horizontalSpacing = "5px";
			formLayout_2.verticalSpacing = "5px";
			formLayout_2.setColumns(["1fr", "80px", "1fr"]);
			formLayout_2.setRows(["50px", "80px", "50px", "35px", "1fr"]);
			group_1.setLayout(formLayout_2);
			(function(container){
				var output_1 = new cpr.controls.Output();
				output_1.value = "토마토 시스템";
				output_1.style.css({
					"font-size" : "30px",
					"text-align" : "center"
				});
				container.addChild(output_1, {
					"colIndex": 0,
					"rowIndex": 0,
					"colSpan": 3,
					"rowSpan": 1
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "2,498,728원";
				output_2.style.css({
					"color" : "blueViolet",
					"font-weight" : "bloder",
					"font-size" : "36px",
					"text-align" : "center"
				});
				container.addChild(output_2, {
					"colIndex": 0,
					"rowIndex": 2,
					"colSpan": 3,
					"rowSpan": 1
				});
				var output_3 = new cpr.controls.Output();
				output_3.value = "2022.01.01~2022.01.31";
				output_3.style.css({
					"font-size" : "18px",
					"text-align" : "center"
				});
				container.addChild(output_3, {
					"colIndex": 0,
					"rowIndex": 3,
					"colSpan": 3,
					"rowSpan": 1
				});
				var output_4 = new cpr.controls.Output();
				output_4.value = "총 19일 152시간 근무";
				output_4.style.css({
					"text-align" : "center"
				});
				container.addChild(output_4, {
					"colIndex": 0,
					"rowIndex": 4,
					"colSpan": 3,
					"rowSpan": 1
				});
				var image_1 = new cpr.controls.Image();
				image_1.src = "https://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Presidential_dollar_coin_reverse.png/596px-Presidential_dollar_coin_reverse.png";
				(function(image_1){
				})(image_1);
				container.addChild(image_1, {
					"colIndex": 1,
					"rowIndex": 1,
					"colSpan": 1,
					"rowSpan": 1
				});
			})(group_1);
			container.addChild(group_1, {
				"colIndex": 0,
				"rowIndex": 0,
				"colSpan": 2,
				"rowSpan": 1
			});
			
			var group_2 = new cpr.controls.Container();
			// Layout
			var formLayout_3 = new cpr.controls.layouts.FormLayout();
			formLayout_3.scrollable = false;
			formLayout_3.horizontalSpacing = "0px";
			formLayout_3.verticalSpacing = "10px";
			formLayout_3.setColumns(["100px", "200px", "1fr", "100px"]);
			formLayout_3.setRows(["1fr", "1fr", "1fr", "1fr", "1fr", "1fr", "1fr"]);
			group_2.setLayout(formLayout_3);
			(function(container){
				var output_5 = new cpr.controls.Output();
				output_5.value = "주휴수당";
				output_5.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_5, {
					"colIndex": 1,
					"rowIndex": 1
				});
				var output_6 = new cpr.controls.Output();
				output_6.value = "세금";
				output_6.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_6, {
					"colIndex": 1,
					"rowIndex": 2
				});
				var output_7 = new cpr.controls.Output();
				output_7.value = "식비";
				output_7.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_7, {
					"colIndex": 1,
					"rowIndex": 3
				});
				var output_8 = new cpr.controls.Output();
				output_8.value = "그 외 수당";
				output_8.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_8, {
					"colIndex": 1,
					"rowIndex": 4
				});
				var output_9 = new cpr.controls.Output();
				output_9.value = "가불";
				output_9.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_9, {
					"colIndex": 1,
					"rowIndex": 5
				});
				var output_10 = new cpr.controls.Output();
				output_10.value = "정산";
				output_10.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_10, {
					"colIndex": 1,
					"rowIndex": 6
				});
				var output_11 = new cpr.controls.Output();
				output_11.value = "Output";
				output_11.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_11, {
					"colIndex": 2,
					"rowIndex": 0
				});
				var output_12 = new cpr.controls.Output();
				output_12.value = "Output";
				output_12.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_12, {
					"colIndex": 2,
					"rowIndex": 1
				});
				var output_13 = new cpr.controls.Output();
				output_13.value = "Output";
				output_13.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_13, {
					"colIndex": 2,
					"rowIndex": 3
				});
				var output_14 = new cpr.controls.Output();
				output_14.value = "Output";
				output_14.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_14, {
					"colIndex": 2,
					"rowIndex": 4
				});
				var output_15 = new cpr.controls.Output();
				output_15.value = "Output";
				output_15.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_15, {
					"colIndex": 2,
					"rowIndex": 5
				});
				var output_16 = new cpr.controls.Output();
				output_16.value = "Output";
				output_16.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_16, {
					"colIndex": 2,
					"rowIndex": 6
				});
				var output_17 = new cpr.controls.Output();
				output_17.value = "Output";
				output_17.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "right"
				});
				container.addChild(output_17, {
					"colIndex": 2,
					"rowIndex": 2
				});
				var output_18 = new cpr.controls.Output();
				output_18.value = "기본급여";
				output_18.style.css({
					"border-bottom-color" : "gainsboro",
					"border-bottom-width" : "1px",
					"font-size" : "24px",
					"border-bottom-style" : "solid",
					"text-align" : "center"
				});
				container.addChild(output_18, {
					"colIndex": 1,
					"rowIndex": 0,
					"colSpan": 1,
					"rowSpan": 1
				});
			})(group_2);
			container.addChild(group_2, {
				"colIndex": 0,
				"rowIndex": 1,
				"colSpan": 2,
				"rowSpan": 8
			});
		}
	});
	app.title = "payslip-part1";
	cpr.core.Platform.INSTANCE.register(app);
})();
