/*
 * App URI: ptj/ptj_main_page
 * Source Location: ptj/ptj_main_page.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("ptj/ptj_main_page", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * ptj_main_page.js
			 * Created at 2022. 1. 4. 오전 11:16:30.
			 *
			 * @author SeongSoo
			 ************************************************/
			
			
			
			
			
			
			/*
			 * "급여 명세서 " 아웃풋에서 click 이벤트 발생 시 호출.
			 * 사용자가 컨트롤을 클릭할 때 발생하는 이벤트.
			 */
			function onOutputClick(/* cpr.events.CMouseEvent */ e){
				/** 
				 * @type cpr.controls.Output
				 */
				var output = e.control;
				app.lookup("ea1").set
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			group_1.style.setClasses(["cl-form-group"]);
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = false;
			formLayout_1.topMargin = "2px";
			formLayout_1.rightMargin = "2px";
			formLayout_1.bottomMargin = "2px";
			formLayout_1.leftMargin = "2px";
			formLayout_1.horizontalSpacing = "2px";
			formLayout_1.verticalSpacing = "2px";
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["100px", "1fr"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setRows(["1fr"]);
			group_1.setLayout(formLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container();
				// Layout
				var formLayout_2 = new cpr.controls.layouts.FormLayout();
				formLayout_2.scrollable = false;
				formLayout_2.topMargin = "5px";
				formLayout_2.rightMargin = "5px";
				formLayout_2.bottomMargin = "5px";
				formLayout_2.leftMargin = "5px";
				formLayout_2.horizontalSpacing = "10px";
				formLayout_2.verticalSpacing = "10px";
				formLayout_2.setColumns(["150px", "150px", "150px", "150px", "1fr", "150px"]);
				formLayout_2.setRows(["1fr"]);
				group_2.setLayout(formLayout_2);
				(function(container){
					var output_1 = new cpr.controls.Output();
					output_1.value = "급여 명세서 ";
					output_1.style.css({
						"text-align" : "center"
					});
					if(typeof onOutputClick == "function") {
						output_1.addEventListener("click", onOutputClick);
					}
					container.addChild(output_1, {
						"colIndex": 1,
						"rowIndex": 0
					});
					var group_3 = new cpr.controls.Container();
					// Layout
					var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
					group_3.setLayout(verticalLayout_1);
					(function(container){
						var group_4 = new cpr.controls.Container();
						// Layout
						var xYLayout_1 = new cpr.controls.layouts.XYLayout();
						group_4.setLayout(xYLayout_1);
						(function(container){
						})(group_4);
						container.addChild(group_4, {
							"width": "400px",
							"height": "20px"
						});
						var output_2 = new cpr.controls.Output();
						output_2.value = "로그아웃";
						output_2.style.css({
							"text-align" : "center"
						});
						container.addChild(output_2, {
							"width": "100px",
							"height": "20px"
						});
					})(group_3);
					container.addChild(group_3, {
						"colIndex": 5,
						"rowIndex": 0
					});
					var output_3 = new cpr.controls.Output();
					output_3.value = "스케줄 관리";
					output_3.style.css({
						"text-align" : "center"
					});
					container.addChild(output_3, {
						"colIndex": 0,
						"rowIndex": 0
					});
					var output_4 = new cpr.controls.Output();
					output_4.value = "사업장 연결";
					output_4.style.css({
						"text-align" : "center"
					});
					container.addChild(output_4, {
						"colIndex": 2,
						"rowIndex": 0
					});
					var output_5 = new cpr.controls.Output();
					output_5.value = "근무지 추가";
					output_5.style.css({
						"text-align" : "center"
					});
					container.addChild(output_5, {
						"colIndex": 3,
						"rowIndex": 0
					});
					var notifier_1 = new cpr.controls.Notifier();
					container.addChild(notifier_1, {
						"colIndex": 4,
						"rowIndex": 0
					});
				})(group_2);
				container.addChild(group_2, {
					"colIndex": 1,
					"rowIndex": 0
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "100px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023px)",
						"hidden": false,
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "100px"
					}, 
					{
						"media": "all and (max-width: 499px)",
						"hidden": false,
						"top": "0px",
						"right": "0px",
						"left": "0px",
						"height": "100px"
					}
				]
			});
			
			var mDIFolder_1 = new cpr.controls.MDIFolder("mdi1");
			
			var tabItem_1 = (function(tabFolder){
				var tabItem_1 = new cpr.controls.TabItem();
				tabItem_1.text = "schedule.clx";
				var embeddedApp_1 = new cpr.controls.EmbeddedApp("ea2");
				cpr.core.App.load("ptj/schedule", function(app) {
					if(app){
						embeddedApp_1.app = app;
					}
				});
				tabItem_1.content = embeddedApp_1;
				return tabItem_1;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_1);
			
			var tabItem_2 = (function(tabFolder){
				var tabItem_2 = new cpr.controls.TabItem();
				tabItem_2.text = "Specification.clx";
				var embeddedApp_2 = new cpr.controls.EmbeddedApp("ea1");
				cpr.core.App.load("ptj/Specification", function(app) {
					if(app){
						embeddedApp_2.app = app;
					}
				});
				tabItem_2.content = embeddedApp_2;
				return tabItem_2;
			})(mDIFolder_1);
			mDIFolder_1.addTabItem(tabItem_2);
			mDIFolder_1.setSelectedTabItem(tabItem_1);
			container.addChild(mDIFolder_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "110px",
						"right": "10px",
						"left": "10px",
						"height": "638px"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023px)",
						"hidden": false,
						"top": "110px",
						"right": "5px",
						"left": "5px",
						"height": "638px"
					}, 
					{
						"media": "all and (max-width: 499px)",
						"hidden": false,
						"top": "110px",
						"right": "3px",
						"left": "3px",
						"height": "638px"
					}
				]
			});
			if(typeof onBodyLoad == "function"){
				app.addEventListener("load", onBodyLoad);
			}
		}
	});
	app.title = "ptj_main_page";
	cpr.core.Platform.INSTANCE.register(app);
})();
