/*
 * App URI: main/login
 * Source Location: main/login.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("main/login", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * main.js
			 * Created at 2021. 12. 29. 오후 4:20:51.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var responsiveXYLayout_1 = new cpr.controls.layouts.ResponsiveXYLayout();
			container.setLayout(responsiveXYLayout_1);
			
			// UI Configuration
			var group_1 = new cpr.controls.Container();
			// Layout
			var verticalLayout_1 = new cpr.controls.layouts.VerticalLayout();
			verticalLayout_1.scrollable = false;
			group_1.setLayout(verticalLayout_1);
			(function(container){
				var group_2 = new cpr.controls.Container();
				// Layout
				var verticalLayout_2 = new cpr.controls.layouts.VerticalLayout();
				verticalLayout_2.distribution = "trailing";
				group_2.setLayout(verticalLayout_2);
				(function(container){
					var checkBox_1 = new cpr.controls.CheckBox("cbx1");
					checkBox_1.text = "Check";
					container.addChild(checkBox_1, {
						"width": "100px",
						"height": "30px"
					});
				})(group_2);
				container.addChild(group_2, {
					"width": "400px",
					"height": "30px"
				});
				var output_1 = new cpr.controls.Output();
				output_1.value = "ID";
				container.addChild(output_1, {
					"width": "100px",
					"height": "20px"
				});
				var inputBox_1 = new cpr.controls.InputBox("ipb1");
				container.addChild(inputBox_1, {
					"width": "100px",
					"height": "20px"
				});
				var output_2 = new cpr.controls.Output();
				output_2.value = "PASSWORD";
				container.addChild(output_2, {
					"width": "100px",
					"height": "20px"
				});
				var inputBox_2 = new cpr.controls.InputBox("ipb2");
				container.addChild(inputBox_2, {
					"width": "100px",
					"height": "20px"
				});
				var button_1 = new cpr.controls.Button();
				button_1.value = "Login";
				container.addChild(button_1, {
					"width": "100px",
					"height": "20px"
				});
				var group_3 = new cpr.controls.Container();
				// Layout
				var formLayout_1 = new cpr.controls.layouts.FormLayout();
				formLayout_1.scrollable = false;
				formLayout_1.topMargin = "2px";
				formLayout_1.rightMargin = "2px";
				formLayout_1.bottomMargin = "2px";
				formLayout_1.leftMargin = "2px";
				formLayout_1.horizontalSpacing = "2px";
				formLayout_1.verticalSpacing = "2px";
				formLayout_1.setColumns(["100px", "1fr", "100px"]);
				formLayout_1.setRows(["1fr"]);
				group_3.setLayout(formLayout_1);
				(function(container){
					var output_3 = new cpr.controls.Output();
					output_3.value = "회원 가입";
					container.addChild(output_3, {
						"colIndex": 0,
						"rowIndex": 0
					});
				})(group_3);
				container.addChild(group_3, {
					"width": "400px",
					"height": "30px"
				});
			})(group_1);
			container.addChild(group_1, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"width": "325px",
						"height": "204px",
						"left": "calc(50% - 162px)",
						"top": "calc(50% - 102px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023px)",
						"hidden": false,
						"width": "159px",
						"height": "204px",
						"left": "calc(50% - 79px)",
						"top": "calc(50% - 102px)"
					}, 
					{
						"media": "all and (max-width: 499px)",
						"hidden": false,
						"width": "111px",
						"height": "204px",
						"left": "calc(50% - 55px)",
						"top": "calc(50% - 102px)"
					}
				]
			});
			
			var output_4 = new cpr.controls.Output();
			output_4.value = "OJT_PROJECT";
			container.addChild(output_4, {
				positions: [
					{
						"media": "all and (min-width: 1024px)",
						"top": "135px",
						"width": "100px",
						"height": "20px",
						"left": "calc(50% - 50px)"
					}, 
					{
						"media": "all and (min-width: 500px) and (max-width: 1023px)",
						"hidden": false,
						"top": "135px",
						"width": "49px",
						"height": "20px",
						"left": "calc(50% - 24px)"
					}, 
					{
						"media": "all and (max-width: 499px)",
						"hidden": false,
						"top": "135px",
						"width": "34px",
						"height": "20px",
						"left": "calc(50% - 17px)"
					}
				]
			});
		}
	});
	app.title = "login";
	cpr.core.Platform.INSTANCE.register(app);
})();
