/*
 * App URI: dialog/test1
 * Source Location: dialog/test1.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("dialog/test1", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * test1.js
			 * Created at 2022. 1. 3. 오후 2:43:10.
			 *
			 * @author SeongSoo
			 ************************************************/;
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (min-width: 400px) and (max-width: 499px)", "new-screen");
			app.supportMedia("all and (max-width: 399px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.setClasses(["cl-form-group"]);
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var formLayout_1 = new cpr.controls.layouts.FormLayout();
			formLayout_1.scrollable = true;
			formLayout_1.topMargin = "0px";
			formLayout_1.rightMargin = "0px";
			formLayout_1.bottomMargin = "0px";
			formLayout_1.leftMargin = "0px";
			formLayout_1.horizontalSpacing = "10px";
			formLayout_1.verticalSpacing = "10px";
			formLayout_1.horizontalSeparatorWidth = 1;
			formLayout_1.verticalSeparatorWidth = 1;
			formLayout_1.setColumns(["1fr", "1fr"]);
			formLayout_1.setUseColumnShade(0, true);
			formLayout_1.setRows(["1fr", "1fr", "1fr", "1fr"]);
			container.setLayout(formLayout_1);
			
			// UI Configuration
			var output_1 = new cpr.controls.Output();
			output_1.value = "Output";
			container.addChild(output_1, {
				"colIndex": 0,
				"rowIndex": 0
			});
			
			var output_2 = new cpr.controls.Output();
			output_2.value = "Output";
			container.addChild(output_2, {
				"colIndex": 0,
				"rowIndex": 1
			});
			
			var output_3 = new cpr.controls.Output();
			output_3.value = "Output";
			container.addChild(output_3, {
				"colIndex": 0,
				"rowIndex": 2
			});
			
			var output_4 = new cpr.controls.Output();
			output_4.value = "Output";
			container.addChild(output_4, {
				"colIndex": 0,
				"rowIndex": 3
			});
		}
	});
	app.title = "test1";
	cpr.core.Platform.INSTANCE.register(app);
})();
