/*
 * App URI: Untitled
 * Source Location: Untitled.clx
 *
 * This file was generated by eXbuilder6 compiler, Don't edit manually.
 */
(function(){
	var app = new cpr.core.App("Untitled", {
		onPrepare: function(loader){
		},
		onCreate: function(/* cpr.core.AppInstance */ app, exports){
			var linker = {};
			// Start - User Script
			/************************************************
			 * Untitled.js
			 * Created at 2021. 12. 31. 오전 11:04:20.
			 *
			 * @author SeongSoo
			 ************************************************/
			
			
			
			/*
			 * 캘린더에서 date-click 이벤트 발생 시 호출.
			 * Calendar의 날짜를 클릭 했을때 발생하는 이벤트.
			 */
			function onCalendarDateClick(/* cpr.events.CDateEvent */ e){
				/** 
				 * @type cpr.controls.Calendar
				 */
				var calendar = e.control;
				app.openDialog("dialog/test1", {width : 400, height : 300}, function(dialog){
					dialog.ready(function(dialogApp){
						// 필요한 경우, 다이얼로그의 앱이 초기화 된 후, 앱 속성을 전달하십시오.
			//			dialogApp.initValue = initValue;
					});
				}).then(function(returnValue){
					
				});
			
			};
			// End - User Script
			
			// Header
			
			app.supportMedia("all and (min-width: 1024px)", "default");
			app.supportMedia("all and (min-width: 500px) and (max-width: 1023px)", "tablet");
			app.supportMedia("all and (max-width: 499px)", "mobile");
			
			// Configure root container
			var container = app.getContainer();
			container.style.css({
				"width" : "100%",
				"height" : "100%"
			});
			
			// Layout
			var xYLayout_1 = new cpr.controls.layouts.XYLayout();
			container.setLayout(xYLayout_1);
			
			// UI Configuration
			var calendar_1 = new cpr.controls.Calendar();
			(function(calendar_1){
			})(calendar_1);
			if(typeof onCalendarDateClick == "function") {
				calendar_1.addEventListener("date-click", onCalendarDateClick);
			}
			container.addChild(calendar_1, {
				"top": "126px",
				"left": "112px",
				"width": "622px",
				"height": "430px"
			});
		}
	});
	app.title = "Untitled";
	cpr.core.Platform.INSTANCE.register(app);
})();
